"use client";
import { Inter } from "next/font/google";
import "./globals.scss";
// import { initializeApp } from "firebase/app";
import "bootstrap/dist/css/bootstrap.min.css";
import { Provider } from "react-redux";
import store from "./redux/Store";
import { useSelector } from "react-redux";
import PopUp from "./components/ui/PopUp";

import { Container } from "react-bootstrap";
// import Header from "./components/public-layout/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// // Your web app's Firebase configuration
// const firebaseConfig = {
//   apiKey: "AIzaSyCsCRQw7HLH9odWIrwENPvxnYMcA04DxDU",
//   authDomain: "medshop-9cc5a.firebaseapp.com",
//   projectId: "medshop-9cc5a",
//   storageBucket: "medshop-9cc5a.appspot.com",
//   messagingSenderId: "828798866487",
//   appId: "1:828798866487:web:c6f5f373bb0dfd39aa5bb2",
// };

// // Initialize Firebase
// const app = initializeApp(firebaseConfig);

function RootLayout({ children }) {
  const selectAlert = useSelector((state) => state.alert);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        {children}
        {selectAlert.visible && (
          <PopUp type={selectAlert.type} message={selectAlert.message} />
        )}
      </body>
    </html>
  );
}
export default function layoutWrapper({ children }) {
  return (
    <Provider store={store}>
      <RootLayout children={children} />
    </Provider>
  );
}
